// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwnjqpdlwzkyrgxybsjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3bmpxcGRsd3preXJneHlic2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjI4NDgsImV4cCI6MjA2OTYzODg0OH0.-FutvUNh8MJ-zxIrCJy14lduMsxa4ji5EpybdQE3L_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});