name: Cleanup All Game Rooms
on:
  schedule:
    - cron: '0 */2 * * *'  # كل ساعتين
  workflow_dispatch:  # يسمح بالتشغيل اليدوي

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup all game rooms
        run: |
          curl -X POST "https://your-project-ref.supabase.co/functions/v1/cleanup-all-rooms" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
